
/*============================================================================
Filename : touch_example.c
Project : QTouch Modular Library
Purpose : Provides sample code snippet to demonstrate how to process and get status from
          touch library.

This file is part of QTouch Modular Library example application.

Important Note: Do not edit this file manually.
                Use QTouch Configurator within Atmel Start to apply any
                modifications to this file.

Usage License: Refer license.h file for license information
Support: Visit http://www.microchip.com/support/hottopics.aspx
               to create MySupport case.

------------------------------------------------------------------------------
Copyright (c) 2020 Microchip. All rights reserved.
------------------------------------------------------------------------------
============================================================================*/

/*----------------------------------------------------------------------------
 *     include files
 *----------------------------------------------------------------------------*/
//#include <atmel_start.h>
#include "touch_example.h"
#include <stdint.h>
#include <stdbool.h>
#define KEY_TOUCHED_MASK 0x80u
/*----------------------------------------------------------------------------
 *   Extern variables
 *----------------------------------------------------------------------------*/
extern volatile uint8_t measurement_done_touch;

/*----------------------------------------------------------------------------
 *   Global variables
 *----------------------------------------------------------------------------*/
uint8_t key_status = 0;
bool isStandby = 0;
bool pressed_last_time = 0;
/*----------------------------------------------------------------------------
 *   prototypes
 *----------------------------------------------------------------------------*/
bool touch_status_display(void);

/*----------------------------------------------------------------------------
 *   function definitions
 *----------------------------------------------------------------------------*/

/*============================================================================
void touch_example(void)
------------------------------------------------------------------------------
Purpose: This function provides sample code snippet to process and check the
         status of touch library
Input  : none
Output : none
Notes  : The content on this function has to be copied to the main() function
         on main.c file.
============================================================================*/
#include "../gpio.h"
#define TOUCHPOINT GPIO(GPIO_PORTC, 9)

/*============================================================================
void touch_status_display(void)
------------------------------------------------------------------------------
Purpose: Sample code snippet to demonstrate how to check the status of the
         sensors
Input  : none
Output : none
Notes  : none
============================================================================*/
bool touch_status_display(void)
{
	bool returnstate = false;
	key_status = get_sensor_state(0) & KEY_TOUCHED_MASK;
	if (key_status != 0u)
	{
		key_status = get_sensor_state(0) & KEY_TOUCHED_MASK;
		if (key_status != 0u && pressed_last_time == 0)
		{
			pressed_last_time = 1;
			if (0u != key_status)
			{
				GPIO_Set_Level(TOUCHPOINT, true);
				returnstate = true;
			}
		}
	}
	else
	{
		key_status = get_sensor_state(0) & KEY_TOUCHED_MASK;
		if (key_status == 0u)
		{
			pressed_last_time = 0;
			GPIO_Set_Level(TOUCHPOINT, false);
		}
	}
	return returnstate;
}


bool Touch_scan(void)
{

	/*
	 * This touch example project demonstrates the usage of QTouch Library firmware for developing touch applications.
	 * To enable sensor tuning, the associated debug information can further be monitored using Atmel Data Visualizer
	 * GUI.
	 *
	 * The following Atmel Start peripheral drivers have been used in this example project along with QTouch Library
	 * middleware.
	 * 1. System Clock - To set CPU clock.
	 * 2. Timer/RTC - To provide periodic scan interval to initiate touch measurement.
	 * 3. USART - To relay touch debug information via EDBG or mEDBG USB bridge to Atmel Data Visualizer GUI.
	 * 4. Global system interrupt should be enabled.
	 *
	 * Note: This is a sample file to provide reference on using touch status in a user application. This file is not
	 * linked to a project build.
	 */
	//set_measure_flag_true();
	touch_process();
	if (measurement_done_touch == 1)
	{
		measurement_done_touch = 0;
		bool touch_status = touch_status_display();
		return touch_status;
	}
	else
	{

		return false;
	}
}

void Touch_scan_task(void){
	Touch_scan();
}