/*============================================================================
Filename : touch_example.h
Project : QTouch Modular Library
Purpose : Provides sample code snippet to demonstrate how to process and get status from
          touch library.

This file is part of QTouch Modular Library example application.

Important Note: Do not edit this file manually.
                Use QTouch Configurator within Atmel Start to apply any
                modifications to this file.

Usage License: Refer license.h file for license information
Support: Visit http://www.microchip.com/support/hottopics.aspx
               to create MySupport case.

------------------------------------------------------------------------------
Copyright (c) 2020 Microchip. All rights reserved.
------------------------------------------------------------------------------
============================================================================*/

#ifndef TOUCH_EXAMPLE_H_
#define TOUCH_EXAMPLE_H_

#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

extern bool Touch_scan(void);
extern void Touch_scan_task(void);
#ifdef __cplusplus
}
#endif
#endif /* TOUCH_EXAMPLE_H_ */
